name: "Javascript lint"

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install standard
        run: |
          npm install standard --location=global

      - name: Lint with standard
        run: |
          standard || true
