name: "Python lint"

on: [push, pull_request]

jobs:
  flake8:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 flake8-import-order darglint codespell

      - name: Lint with flake8
        run: |
          flake8 --statistics

      - name: Check code for common misspellings
        run: |
          codespell -q 3 --skip="*.r,*.xsd,*.json" || true

      - name: Check McCabe complexity
        run: |
          flake8 --max-complexity 10 || true
