name: "Python lint and unit tests"

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8==6.0.0 flake8-import-order==0.18.2 darglint==1.8.1 codespell mypy types-requests werkzeug

      - name: Lint with flake8
        run: |
          flake8 --statistics

      - name: Check static typing
        run: |
          mypy . --explicit-package-bases || true

      - name: Run unit tests
        run: |
          cd unit-tests
          python -m unittest

      - name: Check code for common misspellings
        run: |
          codespell -q 3 --skip="*.css,*.r,*.xsd,*.json,*.map,*.js" || true

      - name: Check McCabe complexity
        run: |
          flake8 --max-complexity 10 || true
